title: EasyCLI
description: Build beautiful CLIs with TypeScript
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: GFM
highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
